### ISSUE TITLE
Strict standards: Declaration of Double\... should be compatible with ...

### ISSUE THREAD

**Issue by DavidGarciaCat** [phpspec/prophecy#310]
Based on my previous issue, reported here https://github.com/phpspec/phpspec/issues/1053, looks like the `Memcached` mock for `getByKey` (and other methods) does not match the signature of the parent class.

My local environment is built with these specs:
- macOS Sierra
- PHP 5.5 (and extensions) via Homebrew

`PHP` version:
```
$ php -v
PHP 5.5.38 (cli) (built: Oct  1 2016 23:03:00)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.14.1~mac-x64-non_zts55, https://blackfire.io, by Blackfireio Inc.
```

Installed `PHP Spec` version:
```
$ composer show phpspec/phpspec*
phpspec/phpspec 2.4.1 Specification-oriented BDD framework for PHP 5.3+
```

Installed `Prophecy` version:
```
$ composer show *prophecy*
phpspec/prophecy v1.4.1 Highly opinionated mocking framework for PHP 5.3+
```

`Memcached` version
```
$ memcached -V
memcached 1.4.33
```

Hope it helps to find the problem!

Regards,

**Comment by stof** [comment]
OK, please first updated Prophecy to 1.6.2. The 1.4.1 version is really old, and I won't provide debugging for it (we already fixed many things since then)

**Comment by stof** [comment]
please give the version of the PHP memcached extension, not of the memcached server (we don't care about it here as it does not provide PHP code). You can have this version in ``phpinfo()``, and also in ``composer show -p`` if the extension exposes it properly

**Comment by DavidGarciaCat** [comment]
Hello @stof 

I updated prophecy, as requested. However the error is still there.

About the PHP Memcached version, these are the details (this is the latest version I can install via Homebrew - I checked yesterday if there were packages to upgrade):

<img width="609" alt="screen shot 2017-01-04 at 10 40 22" src="https://cloud.githubusercontent.com/assets/7809429/21639870/51ec1834-d26a-11e6-9d5e-ef7d2d8097ee.png">

Hope this helps,

**Comment by jakzal** [comment]
This is probably caused by https://github.com/php-memcached-dev/php-memcached/issues/126

**Comment by DavidGarciaCat** [comment]
Thanks for those links @jakzal 

This should confirm the outputs that I am getting, indeed. Also, after a quick read, looks like there are no upcoming plans to fix it from Memcached side due those outputs are not breaking the system. That's sad...
